[package]
name = "raycast"
version = "0.1.0"
authors = ["ChernyshevDS92 <j.phyzic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17"